# Generated by Django 3.2 on 2021-04-06 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210406_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
