# Generated by Django 3.2 on 2021-04-17 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210417_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
